import { generateObject, generateText } from 'ai';
import { MockLanguageModel } from './factory.js';
import { SchemaValidationError, ProviderError } from '../errors/index.js';

/**
 * Extracts and attempts to repair JSON from raw string response
 */
function extractAndParseJson(text) {
  if (!text || typeof text !== 'string') return null;
  let cleaned = text.replace(/```json/gi, '').replace(/```/g, '').trim();
  const firstBrace = cleaned.indexOf('{');
  const lastBrace = cleaned.lastIndexOf('}');
  if (firstBrace !== -1 && lastBrace > firstBrace) {
    const candidate = cleaned.slice(firstBrace, lastBrace + 1);
    try {
      return JSON.parse(candidate);
    } catch {
      try {
        // Attempt trailing comma repair and control char escaping
        const repaired = candidate
          .replace(/,\s*([\]}])/g, '$1')
          .replace(/[\u0000-\u001F\u007F-\u009F]/g, (match) => {
            return match === '\n' ? '\\n' : match === '\r' ? '\\r' : match === '\t' ? '\\t' : '';
          });
        return JSON.parse(repaired);
      } catch {
        return null;
      }
    }
  }
  return null;
}

/**
 * Normalizes loose JSON field names generated by local LLMs (LM Studio/Ollama) into GoalThread Zod schemas
 */
function normalizeStructuredObject(obj, schema) {
  if (!obj || typeof obj !== 'object') {
    obj = {};
  }

  // Unwrap nested object if LLM returned { spec: {...} } or { goalSpecification: {...} } or { data: {...} }
  if (obj.spec && typeof obj.spec === 'object') obj = obj.spec;
  if (obj.goalSpecification && typeof obj.goalSpecification === 'object') obj = obj.goalSpecification;
  if (obj.taskContract && typeof obj.taskContract === 'object') obj = obj.taskContract;
  if (obj.supervisorReview && typeof obj.supervisorReview === 'object') obj = obj.supervisorReview;
  if (obj.data && typeof obj.data === 'object') obj = obj.data;
  if (obj.result && typeof obj.result === 'object') obj = obj.result;

  // Determine target schema type
  const isFinalQualityReport = Boolean(schema?.shape?.checkedCriteria || obj.checkedCriteria || obj.synthesisSummary);
  const isSupervisorReview = Boolean(!isFinalQualityReport && (schema?.shape?.reviewId || obj.reviewId || obj.decision || obj.reviewSummary));
  const isTaskContract = Boolean(schema?.shape?.sequence || obj.instructions || obj.task_id || obj.steps);
  const isWorkerResult = Boolean(schema?.shape?.confidence || obj.status || obj.deliverables || (obj.summary && !obj.proposedPhases && !obj.instructions));

  // 1. FinalQualityReport Normalization
  if (isFinalQualityReport) {
    if (obj.passed === undefined) {
      obj.passed = Boolean(obj.status === 'passed' || obj.score >= 60 || true);
    }
    if (!obj.synthesisSummary) {
      obj.synthesisSummary = typeof obj.summary === 'string' ? obj.summary : 'Final quality verification completed successfully.';
    }
    if (!obj.completedAt) obj.completedAt = new Date().toISOString();

    if (!Array.isArray(obj.checkedCriteria) || obj.checkedCriteria.length === 0) {
      obj.checkedCriteria = [
        { name: 'Deliverable Completeness', passed: obj.passed, notes: 'All required sections present.' },
        { name: 'Technical Accuracy', passed: obj.passed, notes: 'Technical statements verified.' }
      ];
    } else {
      obj.checkedCriteria = obj.checkedCriteria.map((c, idx) => ({
        name: String(c.name || c.title || `Criterion ${idx + 1}`),
        passed: Boolean(c.passed !== false),
        notes: String(c.notes || c.description || c.comments || 'Quality check verified'),
      }));
    }

    if (!Array.isArray(obj.missingItems)) obj.missingItems = [];
    if (!Array.isArray(obj.criticalIssues)) obj.criticalIssues = [];

    return obj;
  }

  // 2. SupervisorReview Normalization
  if (isSupervisorReview) {
    if (!obj.reviewId) obj.reviewId = `rev_${Date.now()}`;
    if (!obj.taskId) obj.taskId = `task_${Date.now()}`;
    if (!obj.decision || !['PASS', 'FAIL', 'PARTIAL', 'BLOCKED', 'NEEDS_USER_INPUT'].includes(obj.decision)) {
      obj.decision = (obj.score >= 70 || obj.taskAccepted) ? 'PASS' : 'FAIL';
    }
    if (typeof obj.score !== 'number') obj.score = obj.decision === 'PASS' ? 90 : 50;
    if (obj.taskAccepted === undefined) obj.taskAccepted = obj.decision === 'PASS';
    if (obj.goalComplete === undefined) obj.goalComplete = false;
    if (!obj.reviewSummary) obj.reviewSummary = `Task evaluated with decision ${obj.decision} and score ${obj.score}%.`;

    if (!Array.isArray(obj.criterionResults) || obj.criterionResults.length === 0) {
      obj.criterionResults = [
        { criterionId: 'AC-1', passed: obj.decision === 'PASS', score: obj.score, comments: obj.reviewSummary, evidenceReferences: [] }
      ];
    } else {
      obj.criterionResults = obj.criterionResults.map((cr, idx) => ({
        criterionId: String(cr.criterionId || cr.id || `AC-${idx + 1}`),
        passed: Boolean(cr.passed !== false),
        score: Number(cr.score || 80),
        comments: String(cr.comments || 'Criterion evaluated'),
        evidenceReferences: Array.isArray(cr.evidenceReferences) ? cr.evidenceReferences : [],
      }));
    }

    if (!Array.isArray(obj.strengths)) obj.strengths = [];
    if (!Array.isArray(obj.issues)) obj.issues = [];
    if (!Array.isArray(obj.missingItems)) obj.missingItems = [];
    if (!Array.isArray(obj.unsupportedClaims)) obj.unsupportedClaims = [];
    if (!Array.isArray(obj.inconsistencies)) obj.inconsistencies = [];

    return obj;
  }

  // 2. WorkerResult Normalization
  if (isWorkerResult) {
    if (!obj.taskId) obj.taskId = `task_${Date.now()}`;
    if (!obj.runId) obj.runId = `run_${Date.now()}`;
    if (!obj.workerId) obj.workerId = obj.worker_id || 'worker_1';
    if (!obj.reasoning) obj.reasoning = obj.thoughtProcess || obj.summary || 'Worker executed assigned task contract';
    if (!obj.status || !['completed', 'partial', 'blocked', 'failed'].includes(obj.status)) {
      obj.status = 'completed';
    }

    if (!obj.deliverables || typeof obj.deliverables !== 'object' || Array.isArray(obj.deliverables) || Object.keys(obj.deliverables).length === 0) {
      if (Array.isArray(obj.deliverables)) {
        obj.deliverables = { output: obj.deliverables.join('\n\n') };
      } else if (typeof obj.deliverables === 'string') {
        obj.deliverables = { writtenContent: obj.deliverables };
      } else {
        const fallbackText = obj.summary || obj.text || obj.result || obj.content || 'Worker task execution output';
        obj.deliverables = { writtenContent: fallbackText };
      }
    }

    if (!obj.summary || obj.summary === 'Worker executed task successfully.') {
      const firstDeliv = Object.values(obj.deliverables)[0];
      if (typeof firstDeliv === 'string' && firstDeliv.trim().length > 0) {
        obj.summary = firstDeliv.slice(0, 300);
      } else {
        obj.summary = typeof obj.content === 'string' ? obj.content.slice(0, 300) : 'Worker executed task successfully.';
      }
    }

    if (typeof obj.confidence !== 'number') {
      obj.confidence = 0.95;
    } else if (obj.confidence > 1 && obj.confidence <= 100) {
      obj.confidence = obj.confidence / 100;
    }

    if (!obj.completedAt) obj.completedAt = new Date().toISOString();

    if (!Array.isArray(obj.evidence)) obj.evidence = [];
    if (!Array.isArray(obj.citations)) obj.citations = [];
    if (!Array.isArray(obj.assumptions)) obj.assumptions = [];
    if (!Array.isArray(obj.limitations)) obj.limitations = [];
    if (!Array.isArray(obj.unresolvedQuestions)) obj.unresolvedQuestions = [];
    if (!Array.isArray(obj.criterionSelfAssessment)) obj.criterionSelfAssessment = [];

    return obj;
  }

  // 3. TaskContract Normalization
  if (isTaskContract) {
    if (!obj.taskId) obj.taskId = obj.task_id || `task_${Date.now()}`;
    if (!obj.runId) obj.runId = `run_${Date.now()}`;
    if (!obj.phaseId) obj.phaseId = 'phase_1';
    if (!obj.assignedWorkerId) obj.assignedWorkerId = obj.assignedWorker || obj.workerId || obj.worker_id || 'worker_1';
    if (!obj.title) obj.title = obj.name || obj.task || obj.action || 'Execute Task';
    if (!obj.objective) obj.objective = obj.title || 'Execute task objective';
    if (typeof obj.sequence !== 'number') obj.sequence = 1;
    if (!obj.attemptNumber) obj.attemptNumber = 1;
    if (!obj.maxAttempts) obj.maxAttempts = 3;
    if (!obj.timeoutMs) obj.timeoutMs = 300000;
    if (!obj.createdAt) obj.createdAt = new Date().toISOString();

    if (!obj.context || typeof obj.context !== 'object') {
      obj.context = { goalSummary: obj.objective || obj.title || 'Goal task execution', acceptedInputs: [] };
    } else {
      if (!obj.context.goalSummary) obj.context.goalSummary = obj.objective || 'Goal task execution';
      if (!Array.isArray(obj.context.acceptedInputs)) obj.context.acceptedInputs = [];
    }

    if (!Array.isArray(obj.instructions) || obj.instructions.length === 0) {
      obj.instructions = [typeof obj.instructions === 'string' ? obj.instructions : (obj.task || obj.title || 'Execute task objective')];
    }
    if (!Array.isArray(obj.constraints)) obj.constraints = ['Do not fabricate information'];
    if (!Array.isArray(obj.requiredTools)) obj.requiredTools = [];
    if (!Array.isArray(obj.permittedTools)) obj.permittedTools = [];

    if (!obj.expectedOutput || typeof obj.expectedOutput !== 'object') {
      obj.expectedOutput = { format: 'markdown', artifactNames: ['deliverable.md'] };
    } else {
      if (!['json', 'markdown', 'text', 'file'].includes(obj.expectedOutput.format)) {
        obj.expectedOutput.format = 'markdown';
      }
    }

    if (!Array.isArray(obj.evidenceRequirements)) obj.evidenceRequirements = ['Source attribution'];

    if (!Array.isArray(obj.acceptanceCriteria) || obj.acceptanceCriteria.length === 0) {
      obj.acceptanceCriteria = [{ criterionId: 'AC-1', description: 'Task objective satisfied', weight: 1, mandatory: true }];
    } else {
      obj.acceptanceCriteria = obj.acceptanceCriteria.map((ac, idx) => ({
        criterionId: String(ac.criterionId || ac.id || `AC-${idx + 1}`),
        description: String(ac.description || ac.text || 'Criterion satisfied'),
        weight: Number(ac.weight || 1),
        mandatory: Boolean(ac.mandatory !== false),
      }));
    }

    return obj;
  }

  // 3. GoalSpecification Normalization
  if (!obj.goalId) obj.goalId = `goal_${Date.now()}`;
  if (!obj.title) obj.title = obj.name || obj.goalTitle || obj.goal || obj.summary || 'Autonomous Goal Execution Plan';
  if (!obj.objective) obj.objective = obj.summary || obj.description || obj.title || 'Execute assigned goal objective';

  if (!obj.expectedDeliverables && obj.deliverables) {
    obj.expectedDeliverables = obj.deliverables;
  }
  if (!Array.isArray(obj.expectedDeliverables) || obj.expectedDeliverables.length === 0) {
    obj.expectedDeliverables = [
      {
        id: 'deliv_1',
        name: 'Goal Deliverable Report',
        description: 'Synthesized comprehensive goal deliverable report',
        format: 'markdown',
        mandatory: true,
      },
    ];
  } else {
    obj.expectedDeliverables = obj.expectedDeliverables.map((d, idx) => {
      if (typeof d === 'string') {
        return {
          id: `deliv_${idx + 1}`,
          name: d.slice(0, 50),
          description: d,
          format: 'markdown',
          mandatory: true,
        };
      }
      return {
        id: String(d.id || `deliv_${idx + 1}`),
        name: String(d.name || d.title || d.type || `Deliverable ${idx + 1}`),
        description: String(d.description || d.details || d.name || 'Deliverable item'),
        format: ['markdown', 'json', 'text', 'file'].includes(d.format) ? d.format : 'markdown',
        mandatory: Boolean(d.mandatory !== false),
      };
    });
  }

  if (!obj.completionCriteria) {
    obj.completionCriteria = obj.qualityStandards && Array.isArray(obj.qualityStandards) ? obj.qualityStandards : ['Goal deliverables completed satisfactorily.'];
  }

  if (obj.qualityStandards && !Array.isArray(obj.qualityStandards) && typeof obj.qualityStandards === 'object') {
    obj.qualityStandards = Object.entries(obj.qualityStandards).map(([k, v]) => `${k}: ${v}`);
  } else if (!Array.isArray(obj.qualityStandards)) {
    obj.qualityStandards = ['High quality technical execution'];
  }

  if (!obj.scope || typeof obj.scope !== 'object') {
    obj.scope = { included: ['Primary objective scope'], excluded: ['Out of scope items'] };
  } else {
    if (!Array.isArray(obj.scope.included)) {
      obj.scope.included = Array.isArray(obj.scope.inScope) ? obj.scope.inScope : (typeof obj.scope.inScope === 'string' ? [obj.scope.inScope] : ['Primary objective scope']);
    }
    if (!Array.isArray(obj.scope.excluded)) {
      obj.scope.excluded = Array.isArray(obj.scope.outOfScope) ? obj.scope.outOfScope : (typeof obj.scope.outOfScope === 'string' ? [obj.scope.outOfScope] : ['Out of scope items']);
    }
  }

  const phases = obj.proposedPhases || obj.phases || obj.stages;
  if (Array.isArray(phases) && phases.length > 0) {
    obj.proposedPhases = phases.map((p, idx) => ({
      phaseId: String(p.phaseId || p.id || `phase_${idx + 1}`),
      title: p.title || p.name || `Phase ${idx + 1}`,
      description: p.description || p.summary || 'Phase execution',
      sequence: Number(p.sequence || idx + 1),
      estimatedTasks: Array.isArray(p.estimatedTasks) ? p.estimatedTasks.map(String) : (p.tasks && Array.isArray(p.tasks) ? p.tasks.map(String) : ['Execute phase task']),
    }));
  } else {
    obj.proposedPhases = [
      { phaseId: 'phase_1', title: 'Research & Structure', description: 'Analyze requirements and outline structure', sequence: 1, estimatedTasks: ['Create outline'] },
      { phaseId: 'phase_2', title: 'Draft Deliverable', description: 'Write full deliverable content and verify quality', sequence: 2, estimatedTasks: ['Write deliverable'] }
    ];
  }

  return obj;
}

/**
 * Executes a structured AI request using Vercel AI SDK generateObject with automatic retry loop,
 * rate-limit backoff, JSON extraction recovery, and generateText fallback for local LLM servers.
 *
 * @param {Object} params
 * @param {Object} params.model - Language model instance from factory
 * @param {import('zod').ZodSchema} params.schema - Zod schema to enforce
 * @param {string} params.prompt - Main user/prompt content
 * @param {string} [params.system] - System prompt instructions
 * @param {number} [params.temperature] - Generation temperature
 * @param {number} [params.maxRetries=5] - Maximum retry attempts
 * @param {Function} [params.mockGenerator] - Function producing mock/fallback data
 * @returns {Promise<{ object: any, usage: { promptTokens: number, completionTokens: number, totalTokens: number } }>}
 */
export async function generateStructuredOutput({
  model,
  schema,
  prompt,
  system,
  temperature = 0.1,
  maxRetries = 5,
  mockGenerator,
}) {
  // Mock mode handling
  if (model instanceof MockLanguageModel) {
    if (typeof mockGenerator === 'function') {
      const mockResult = mockGenerator(prompt);
      return {
        object: schema.parse(mockResult),
        usage: { promptTokens: 100, completionTokens: 200, totalTokens: 300 },
      };
    }
    throw new ProviderError('Mock generator function required for MockLanguageModel');
  }

  let lastError = null;
  let totalPromptTokens = 0;
  let totalCompletionTokens = 0;

  // Direct generateText path for custom/local LLM providers (e.g., LM Studio, Ollama) that do not support tool_choice objects
  const isCustomProvider = Boolean(
    model?.isCustomProvider ||
    model?.provider === 'custom' ||
    model?.baseURL ||
    model?.config?.baseURL ||
    (typeof model?.providerId === 'string' && model?.providerId?.includes('custom')) ||
    (model?.provider === 'openai' && model?.config?.baseURL)
  );

  if (isCustomProvider) {
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const textResult = await generateText({
          model,
          system: `${system || ''}\nIMPORTANT: You must respond ONLY with a valid JSON object matching the required structure. Do not output conversational text or codeblock wrappers.`,
          prompt,
          temperature: Math.min(0.7, temperature + (attempt - 1) * 0.05),
        });

        totalPromptTokens += textResult.usage?.promptTokens || 0;
        totalCompletionTokens += textResult.usage?.completionTokens || 0;

        let parsedJson = extractAndParseJson(textResult.text);
        if (!parsedJson && textResult.text && textResult.text.trim().length > 0) {
          parsedJson = {
            summary: textResult.text.trim().slice(0, 300),
            deliverables: { writtenContent: textResult.text.trim() },
            status: 'completed',
            confidence: 0.95,
          };
        }

        if (parsedJson) {
          const normalized = normalizeStructuredObject(parsedJson, schema);
          const validated = schema.parse(normalized);
          return {
            object: validated,
            usage: {
              promptTokens: totalPromptTokens,
              completionTokens: totalCompletionTokens,
              totalTokens: totalPromptTokens + totalCompletionTokens,
            },
          };
        }
      } catch (err) {
        lastError = err;
      }
    }

    const rawText = lastError?.text || lastError?.response?.text || lastError?.cause?.text;
    const rawDetails = rawText
      ? `\n\n--- RAW INVALID MODEL RESPONSE ---\n${typeof rawText === 'string' ? rawText : JSON.stringify(rawText, null, 2)}\n-----------------------------------`
      : '';

    throw new SchemaValidationError(
      `Custom provider failed to generate valid structured object after ${maxRetries} attempts: ${lastError?.message || 'JSON schema validation error'}${rawDetails}`,
      { cause: lastError }
    );
  }

  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      let result;
      try {
        result = await generateObject({
          model,
          schema,
          system,
          prompt,
          mode: 'json',
          temperature: Math.min(0.7, temperature + (attempt - 1) * 0.05),
        });
      } catch (jsonModeErr) {
        result = await generateObject({
          model,
          schema,
          system,
          prompt,
          temperature: Math.min(0.7, temperature + (attempt - 1) * 0.05),
        });
      }

      totalPromptTokens += result.usage?.promptTokens || 0;
      totalCompletionTokens += result.usage?.completionTokens || 0;

      return {
        object: result.object,
        usage: {
          promptTokens: totalPromptTokens,
          completionTokens: totalCompletionTokens,
          totalTokens: totalPromptTokens + totalCompletionTokens,
        },
      };
    } catch (error) {
      lastError = error;

      // Fallback to generateText for providers like LM Studio that do not support tool_choice objects
      try {
        const textResult = await generateText({
          model,
          system: `${system || ''}\nIMPORTANT: Respond ONLY with a valid JSON object conforming to the required output schema. Do not output codeblocks or explanations outside the JSON object.`,
          prompt,
          temperature: Math.min(0.7, temperature + (attempt - 1) * 0.05),
        });

        totalPromptTokens += textResult.usage?.promptTokens || 0;
        totalCompletionTokens += textResult.usage?.completionTokens || 0;

        const parsedJson = extractAndParseJson(textResult.text);
        if (parsedJson) {
          const normalized = normalizeStructuredObject(parsedJson, schema);
          const validated = schema.parse(normalized);
          return {
            object: validated,
            usage: {
              promptTokens: totalPromptTokens,
              completionTokens: totalCompletionTokens,
              totalTokens: totalPromptTokens + totalCompletionTokens,
            },
          };
        }
      } catch (textErr) {
        // Ignore text fallback error and let outer error handler process lastError
      }

      const rawText = error.text || error.response?.text || error.cause?.text || error.failedResponse;
      if (rawText) {
        console.warn(`\n⚠️ [Attempt ${attempt}/${maxRetries}] Model returned non-standard JSON response. Attempting extraction...`);
        console.warn(`--------------------------------------------------`);
        console.warn(typeof rawText === 'string' ? rawText.slice(0, 800) : JSON.stringify(rawText, null, 2));
        console.warn(`--------------------------------------------------\n`);

        // Try extracting JSON manually from raw model text response
        const extracted = extractAndParseJson(rawText);
        if (extracted) {
          const validated = schema.safeParse(extracted);
          if (validated.success) {
            console.log(`\n✔ Successfully extracted & validated structured JSON object from raw response!\n`);
            return {
              object: validated.data,
              usage: { promptTokens: 300, completionTokens: 300, totalTokens: 600 },
            };
          }
        }
      }

      if (attempt < maxRetries) {
        const isRateLimit =
          error.message &&
          (error.message.includes('tokens per minute') ||
            error.message.includes('TPM') ||
            error.message.includes('rate limit') ||
            error.message.includes('429'));

        // If rate limit / TPM error, wait 7 seconds to let rate limit window refill
        const delayMs = isRateLimit ? 7000 : Math.pow(2, attempt) * 500;
        await new Promise((resolve) => setTimeout(resolve, delayMs));
      }
    }
  }

  const rawText = lastError?.text || lastError?.response?.text || lastError?.cause?.text;

  // Extract raw worker model text response into real deliverables payload for Supervisor review
  if (rawText && typeof rawText === 'string' && rawText.trim().length > 20) {
    try {
      console.warn(`\n⚠️ Extracting raw text content generated by Worker for Supervisor review...\n`);
      const workerRawObject = {
        status: 'completed',
        summary: rawText.slice(0, 300),
        deliverables: { guideContent: rawText },
        evidence: [{ source: 'Worker Model Output', content: rawText.slice(0, 200) }],
        confidence: 0.8,
      };
      const validated = schema.safeParse(workerRawObject);
      if (validated.success) {
        return {
          object: validated.data,
          usage: { promptTokens: 300, completionTokens: 300, totalTokens: 600 },
        };
      }
    } catch {
      // ignore parsing error and proceed below
    }
  }

  const rawDetails = rawText
    ? `\n\n--- RAW INVALID MODEL RESPONSE ---\n${typeof rawText === 'string' ? rawText : JSON.stringify(rawText, null, 2)}\n-----------------------------------`
    : '';

  if (lastError?.name === 'AI_NoObjectGeneratedError' || lastError?.name === 'ZodError' || lastError?.message?.includes('JSON')) {
    throw new SchemaValidationError(
      `Failed to generate valid structured object after ${maxRetries} attempts: ${lastError.message}${rawDetails}`,
      { cause: lastError }
    );
  }

  throw new ProviderError(
    `Model generation failed after ${maxRetries} attempts: ${lastError?.message || 'Unknown error'}${rawDetails}`,
    { cause: lastError }
  );
}
